"use client";
import Link from 'next/link';
import BrandMark from '@/components/BrandMark';
import { ArrowLeft, ArrowUpRight, Github, Check } from 'lucide-react';
import { motion, useReducedMotion } from 'framer-motion';
import type { Project } from '@/lib/projects';
import { projectsData } from '@/lib/projects';
export default function ProjectPageClient({project}:{project:Project}) {
 const reduced=useReducedMotion();
 const index=projectsData.findIndex(p=>p.id===project.id);
 const next=projectsData[(index+1)%projectsData.length];
 return <main className="case-page"><header className="nav"><Link className="brand" href="/" aria-label="Khaled Yousef home"><BrandMark/></Link><span className="nav-name">KHALED YOUSEF<br/><small>QUALITY × INTELLIGENCE</small></span><nav><Link href="/#work"><ArrowLeft size={15}/> All projects</Link><a href="mailto:kyousefju@gmail.com">Let’s talk <ArrowUpRight size={15}/></a></nav></header><motion.section className="section case-hero" initial={reduced?false:{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.8}}><p className="eyebrow">SELECTED WORK / 0{index+1} <span className="case-category">{project.category}</span></p><h1>{project.title}</h1><p className="case-tagline">{project.tagline}</p><div className="case-meta"><div><span className="eyebrow">BUILT WITH</span><div className="tags">{project.tech.map(t=><span key={t}>{t}</span>)}</div></div><div className="case-actions"><a className="text-link" href={project.github} target="_blank" rel="noopener noreferrer"><Github size={18}/> Explore source <ArrowUpRight size={17}/></a>{project.live&&<a className="case-live" href={project.live} target="_blank" rel="noopener noreferrer">Visit product <ArrowUpRight size={17}/></a>}</div></div></motion.section><section className="case-body section"><div className="case-overview"><p className="eyebrow">01 / THE IDEA</p><h2>From possibility<br/>to <em>practice.</em></h2></div><div><p className="case-description">{project.description}</p><p className="eyebrow case-capabilities">02 / INSIDE THE SYSTEM</p><div className="case-features">{project.features.map((f,i)=><motion.div key={f} initial={reduced?false:{opacity:0,y:12}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.04}}><span>0{i+1}</span><p>{f}</p><Check size={16}/></motion.div>)}</div></div></section><section className="section case-next"><p className="eyebrow">CONTINUE EXPLORING / 0{(index+1)%projectsData.length+1}</p><Link href={`/projects/${next.id}`}><h2>{next.title}</h2><ArrowUpRight size={50}/></Link></section><footer className="site-footer"><Link href="/#work">← ALL SELECTED WORK</Link><span>© {new Date().getFullYear()} KHALED YOUSEF</span><a href="mailto:kyousefju@gmail.com">LET’S TALK ↗</a></footer></main>
}
